package migrate

import (
	"context"
	"database/sql"
	"fmt"
	"sync"
	"time"

	"go.uber.org/zap"
)

// TableFunctions holds repo function names and AUDIT/REPO flags for one table.
// One map entry per schema.table, loaded at startup by UpdateHist / Wire.
type TableFunctions struct {
	Schema   string
	Table    string
	Insert   string
	Update   string
	Delete   string
	Get      string
	Upsert   string // also generated by migrate; optional for callers
	List     string
	ListRepo bool // registry boo_repo for list (false when table has no children)
	Audit    bool // table COMMENT AUDIT=true
	Repo     bool // table COMMENT REPO=true
}

// functionExec tracks in-memory Dirty/LastExecuted for one store function.
type functionExec struct {
	Schema       string
	Table        string
	FunctionName string
	Dirty        bool
	LastExecuted time.Time
}

var (
	functionsMu sync.RWMutex
	functions   = map[string]TableFunctions{}

	executionsMu sync.RWMutex
	executions   = map[string]functionExec{}
)

func functionsKey(schema, table string) string {
	return schema + "." + table
}

func executionKey(schema, table, functionName string) string {
	return schema + "." + table + "." + functionName
}

// Functions returns the loaded entry for schema.table.
func Functions(schema, table string) (TableFunctions, bool) {
	functionsMu.RLock()
	defer functionsMu.RUnlock()
	fn, ok := functions[functionsKey(schema, table)]
	return fn, ok
}

// MustFunctions returns function names or an error when the registry entry is missing.
func MustFunctions(schema, table string) (TableFunctions, error) {
	fn, ok := Functions(schema, table)
	if !ok {
		return TableFunctions{}, fmt.Errorf("migrate: no repo functions registered for %s.%s", schema, table)
	}
	if fn.Insert == "" && fn.Get == "" && fn.Update == "" && fn.Delete == "" {
		return TableFunctions{}, fmt.Errorf("migrate: no repo functions registered for %s.%s", schema, table)
	}
	return fn, nil
}

// RepoEnabled reports whether the table COMMENT had REPO=true at last load.
func RepoEnabled(schema, table string) bool {
	fn, ok := Functions(schema, table)
	return ok && fn.Repo
}

// AuditEnabled reports whether the table COMMENT had AUDIT=true at last load.
func AuditEnabled(schema, table string) bool {
	fn, ok := Functions(schema, table)
	return ok && fn.Audit
}

// LastExecuted returns the last known execution time for a repo function.
func LastExecuted(schema, table, functionName string) (time.Time, bool) {
	if functionName == "" {
		return time.Time{}, false
	}
	executionsMu.RLock()
	defer executionsMu.RUnlock()
	ex, ok := executions[executionKey(schema, table, functionName)]
	if !ok || ex.LastExecuted.IsZero() {
		return time.Time{}, false
	}
	return ex.LastExecuted, true
}

// MarkRepoExecuted sets Dirty and LastExecuted=now for one function after a
// successful repo call. No-op when functionName is empty.
func MarkRepoExecuted(schema, table, functionName string) {
	if functionName == "" {
		return
	}
	now := time.Now().UTC()
	executionsMu.Lock()
	defer executionsMu.Unlock()
	key := executionKey(schema, table, functionName)
	ex := executions[key]
	ex.Schema = schema
	ex.Table = table
	ex.FunctionName = functionName
	ex.Dirty = true
	ex.LastExecuted = now
	executions[key] = ex
}

// LoadTableFunctions reloads the global map from audit.tbl_repo_function, then
// overlays AUDIT/REPO flags from discovered table comments (authoritative).
func LoadTableFunctions(ctx context.Context, db *sql.DB, tables []Table) error {
	if db == nil {
		return fmt.Errorf("migrate: database is required to load repo functions")
	}

	// Ensure registry exists even when no REPO tables were applied this run.
	if _, err := db.ExecContext(ctx, buildRepoRegistrySQL()); err != nil {
		return fmt.Errorf("ensure repo registry: %w", err)
	}

	rows, err := db.QueryContext(ctx, `
SELECT DISTINCT ON (str_schema_name, str_table_name, str_operation)
	str_schema_name,
	str_table_name,
	str_operation,
	str_function_name,
	boo_audit,
	boo_repo
FROM audit.tbl_repo_function
ORDER BY str_schema_name, str_table_name, str_operation, int_version DESC
`)
	if err != nil {
		return fmt.Errorf("load repo functions: %w", err)
	}
	defer rows.Close()

	next := map[string]TableFunctions{}
	for rows.Next() {
		var schema, table, operation, name string
		var audit, repo bool
		if err := rows.Scan(&schema, &table, &operation, &name, &audit, &repo); err != nil {
			return fmt.Errorf("scan repo functions: %w", err)
		}
		key := functionsKey(schema, table)
		fn := next[key]
		fn.Schema = schema
		fn.Table = table
		switch operation {
		case "insert":
			fn.Insert = name
			fn.Audit = audit
			fn.Repo = repo
		case "update":
			fn.Update = name
		case "delete":
			fn.Delete = name
		case "get":
			fn.Get = name
		case "upsert":
			fn.Upsert = name
		case "list":
			fn.List = name
			fn.ListRepo = repo
		}
		next[key] = fn
	}
	if err := rows.Err(); err != nil {
		return err
	}

	// Comment discovery is authoritative for AUDIT/REPO (and covers audit-only tables).
	for _, t := range tables {
		key := functionsKey(t.Schema, t.Name)
		fn := next[key]
		fn.Schema = t.Schema
		fn.Table = t.Name
		fn.Audit = t.Audit
		fn.Repo = t.Repo
		next[key] = fn
	}

	nextExec, err := loadFunctionExecutions(ctx, db)
	if err != nil {
		return err
	}

	functionsMu.Lock()
	functions = next
	functionsMu.Unlock()

	executionsMu.Lock()
	executions = nextExec
	executionsMu.Unlock()
	return nil
}

func loadFunctionExecutions(ctx context.Context, db *sql.DB) (map[string]functionExec, error) {
	rows, err := db.QueryContext(ctx, `
SELECT str_schema_name,
	str_table_name,
	str_function_name,
	dt_last_executed
FROM audit.tbl_repo_function_exec
`)
	if err != nil {
		return nil, fmt.Errorf("load repo function executions: %w", err)
	}
	defer rows.Close()

	out := map[string]functionExec{}
	for rows.Next() {
		var schema, table, name string
		var last time.Time
		if err := rows.Scan(&schema, &table, &name, &last); err != nil {
			return nil, fmt.Errorf("scan repo function execution: %w", err)
		}
		key := executionKey(schema, table, name)
		out[key] = functionExec{
			Schema:       schema,
			Table:        table,
			FunctionName: name,
			Dirty:        false,
			LastExecuted: last.UTC(),
		}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotFunctions returns a copy of the in-memory map (for tests/debug).
func SnapshotFunctions() map[string]TableFunctions {
	functionsMu.RLock()
	defer functionsMu.RUnlock()
	out := make(map[string]TableFunctions, len(functions))
	for k, v := range functions {
		out[k] = v
	}
	return out
}

func clearDirtyIfUnchanged(schema, table, functionName string, syncedAt time.Time) {
	executionsMu.Lock()
	defer executionsMu.Unlock()
	key := executionKey(schema, table, functionName)
	ex, ok := executions[key]
	if !ok {
		return
	}
	// Keep Dirty if a newer execution arrived while we were writing.
	if ex.LastExecuted.After(syncedAt) {
		return
	}
	ex.Dirty = false
	executions[key] = ex
}

// SyncDirtyLastExecuted writes pending LastExecuted values to
// audit.tbl_repo_function_exec for Dirty entries only. Updates only when the
// in-memory value is greater than the stored one. Always clears in-memory
// Dirty afterward (unless a newer MarkRepoExecuted happened mid-sync).
func SyncDirtyLastExecuted(ctx context.Context, db *sql.DB) error {
	if db == nil {
		return fmt.Errorf("migrate: database is required to sync last executed")
	}

	executionsMu.Lock()
	defer executionsMu.Unlock()

	for key, ex := range executions {
		if !ex.Dirty || ex.LastExecuted.IsZero() {
			continue
		}
		syncedAt := ex.LastExecuted
		_, err := db.ExecContext(ctx, `
INSERT INTO audit.tbl_repo_function_exec (
	str_schema_name, str_table_name, str_function_name, dt_last_executed
) VALUES ($1, $2, $3, $4)
ON CONFLICT (str_schema_name, str_table_name, str_function_name) DO UPDATE
SET dt_last_executed = EXCLUDED.dt_last_executed
WHERE audit.tbl_repo_function_exec.dt_last_executed < EXCLUDED.dt_last_executed
`, ex.Schema, ex.Table, ex.FunctionName, syncedAt.UTC())
		if err != nil {
			return fmt.Errorf("sync last executed for %s.%s.%s: %w", ex.Schema, ex.Table, ex.FunctionName, err)
		}
		// Map is locked for the whole sync, so LastExecuted cannot advance mid-write.
		ex.Dirty = false
		executions[key] = ex
	}
	return nil
}

func (s *Service) startLastExecutedSync(ctx context.Context) {
	if ctx == nil || s == nil || s.db == nil {
		return
	}
	go func() {
		ticker := time.NewTicker(time.Minute)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				if err := SyncDirtyLastExecuted(ctx, s.db); err != nil {
					logger := s.logger
					if logger == nil {
						logger = zap.NewNop()
					}
					logger.Warn("migrate sync last executed failed", zap.Error(err))
				}
			}
		}
	}()
}
