package currency

// ISO4217Catalog is the ISO 4217 currency registry.
var ISO4217Catalog = map[string]CatalogEntry{
	"AED": {Name: "UAE Dirham", Symbol: "AED"},
	"AFN": {Name: "Afghan Afghani", Symbol: "AFN"},
	"ALL": {Name: "Albanian Lek", Symbol: "ALL"},
	"AMD": {Name: "Armenian Dram", Symbol: "AMD"},
	"AOA": {Name: "Angolan Kwanza", Symbol: "AOA"},
	"ARS": {Name: "Argentine Peso", Symbol: "ARS"},
	"AUD": {Name: "Australian Dollar", Symbol: "A$"},
	"AWG": {Name: "Aruban Florin", Symbol: "AWG"},
	"AZN": {Name: "Azerbaijani Manat", Symbol: "AZN"},
	"BAM": {Name: "Bosnia-Herzegovina Convertible Mark", Symbol: "BAM"},
	"BBD": {Name: "Barbadian Dollar", Symbol: "BBD"},
	"BDT": {Name: "Bangladeshi Taka", Symbol: "৳"},
	"BGN": {Name: "Bulgarian Lev", Symbol: "BGN"},
	"BHD": {Name: "Bahraini Dinar", Symbol: "BHD"},
	"BIF": {Name: "Burundian Franc", Symbol: "BIF"},
	"BMD": {Name: "Bermudian Dollar", Symbol: "BMD"},
	"BND": {Name: "Brunei Dollar", Symbol: "BND"},
	"BOB": {Name: "Bolivian Boliviano", Symbol: "BOB"},
	"BOV": {Name: "Bolivian Mvdol", Symbol: "BOV"},
	"BRL": {Name: "Brazilian Real", Symbol: "R$"},
	"BSD": {Name: "Bahamian Dollar", Symbol: "BSD"},
	"BTN": {Name: "Bhutanese Ngultrum", Symbol: "BTN"},
	"BWP": {Name: "Botswanan Pula", Symbol: "BWP"},
	"BYN": {Name: "Belarusian Ruble", Symbol: "BYN"},
	"BZD": {Name: "Belize Dollar", Symbol: "BZD"},
	"CAD": {Name: "Canadian Dollar", Symbol: "C$"},
	"CDF": {Name: "Congolese Franc", Symbol: "CDF"},
	"CHE": {Name: "WIR Euro", Symbol: "CHE"},
	"CHF": {Name: "Swiss Franc", Symbol: "Fr"},
	"CHW": {Name: "WIR Franc", Symbol: "CHW"},
	"CLF": {Name: "Chilean Unit of Account (UF)", Symbol: "CLF"},
	"CLP": {Name: "Chilean Peso", Symbol: "CLP"},
	"CNY": {Name: "Chinese Yuan", Symbol: "¥"},
	"COP": {Name: "Colombian Peso", Symbol: "COP"},
	"COU": {Name: "Unidad de Valor Real", Symbol: "COU"},
	"CRC": {Name: "Costa Rican Colón", Symbol: "CRC"},
	"CUC": {Name: "Cuban Convertible Peso", Symbol: "CUC"},
	"CUP": {Name: "Cuban Peso", Symbol: "CUP"},
	"CVE": {Name: "Cape Verdean Escudo", Symbol: "CVE"},
	"CZK": {Name: "Czech Koruna", Symbol: "CZK"},
	"DJF": {Name: "Djiboutian Franc", Symbol: "DJF"},
	"DKK": {Name: "Danish Krone", Symbol: "kr"},
	"DOP": {Name: "Dominican Peso", Symbol: "DOP"},
	"DZD": {Name: "Algerian Dinar", Symbol: "DZD"},
	"EGP": {Name: "Egyptian Pound", Symbol: "EGP"},
	"ERN": {Name: "Eritrean Nakfa", Symbol: "ERN"},
	"ETB": {Name: "Ethiopian Birr", Symbol: "ETB"},
	"EUR": {Name: "Euro", Symbol: "€"},
	"FJD": {Name: "Fijian Dollar", Symbol: "FJD"},
	"FKP": {Name: "Falkland Islands Pound", Symbol: "FKP"},
	"GBP": {Name: "British Pound Sterling", Symbol: "£"},
	"GEL": {Name: "Georgian Lari", Symbol: "GEL"},
	"GHS": {Name: "Ghanaian Cedi", Symbol: "GHS"},
	"GIP": {Name: "Gibraltar Pound", Symbol: "GIP"},
	"GMD": {Name: "Gambian Dalasi", Symbol: "GMD"},
	"GNF": {Name: "Guinean Franc", Symbol: "GNF"},
	"GTQ": {Name: "Guatemalan Quetzal", Symbol: "GTQ"},
	"GYD": {Name: "Guyanaese Dollar", Symbol: "GYD"},
	"HKD": {Name: "Hong Kong Dollar", Symbol: "HK$"},
	"HNL": {Name: "Honduran Lempira", Symbol: "HNL"},
	"HTG": {Name: "Haitian Gourde", Symbol: "HTG"},
	"HUF": {Name: "Hungarian Forint", Symbol: "HUF"},
	"IDR": {Name: "Indonesian Rupiah", Symbol: "IDR"},
	"ILS": {Name: "Israeli New Shekel", Symbol: "₪"},
	"INR": {Name: "Indian Rupee", Symbol: "₹"},
	"IQD": {Name: "Iraqi Dinar", Symbol: "IQD"},
	"IRR": {Name: "Iranian Rial", Symbol: "IRR"},
	"ISK": {Name: "Icelandic Króna", Symbol: "kr"},
	"JMD": {Name: "Jamaican Dollar", Symbol: "JMD"},
	"JOD": {Name: "Jordanian Dinar", Symbol: "JOD"},
	"JPY": {Name: "Japanese Yen", Symbol: "¥"},
	"KES": {Name: "Kenyan Shilling", Symbol: "KES"},
	"KGS": {Name: "Kyrgystani Som", Symbol: "KGS"},
	"KHR": {Name: "Cambodian Riel", Symbol: "KHR"},
	"KMF": {Name: "Comorian Franc", Symbol: "KMF"},
	"KPW": {Name: "North Korean Won", Symbol: "KPW"},
	"KRW": {Name: "South Korean Won", Symbol: "₩"},
	"KWD": {Name: "Kuwaiti Dinar", Symbol: "KWD"},
	"KYD": {Name: "Cayman Islands Dollar", Symbol: "KYD"},
	"KZT": {Name: "Kazakhstani Tenge", Symbol: "KZT"},
	"LAK": {Name: "Laotian Kip", Symbol: "LAK"},
	"LBP": {Name: "Lebanese Pound", Symbol: "LBP"},
	"LKR": {Name: "Sri Lankan Rupee", Symbol: "LKR"},
	"LRD": {Name: "Liberian Dollar", Symbol: "LRD"},
	"LSL": {Name: "Lesotho Loti", Symbol: "LSL"},
	"LYD": {Name: "Libyan Dinar", Symbol: "LYD"},
	"MAD": {Name: "Moroccan Dirham", Symbol: "MAD"},
	"MDL": {Name: "Moldovan Leu", Symbol: "MDL"},
	"MGA": {Name: "Malagasy Ariary", Symbol: "MGA"},
	"MKD": {Name: "Macedonian Denar", Symbol: "MKD"},
	"MMK": {Name: "Myanma Kyat", Symbol: "MMK"},
	"MNT": {Name: "Mongolian Tugrik", Symbol: "MNT"},
	"MOP": {Name: "Macanese Pataca", Symbol: "MOP"},
	"MRU": {Name: "Mauritanian Ouguiya", Symbol: "MRU"},
	"MUR": {Name: "Mauritian Rupee", Symbol: "MUR"},
	"MVR": {Name: "Maldivian Rufiyaa", Symbol: "MVR"},
	"MWK": {Name: "Malawian Kwacha", Symbol: "MWK"},
	"MXN": {Name: "Mexican Peso", Symbol: "$"},
	"MXV": {Name: "Mexican Investment Unit", Symbol: "MXV"},
	"MYR": {Name: "Malaysian Ringgit", Symbol: "MYR"},
	"MZN": {Name: "Mozambican Metical", Symbol: "MZN"},
	"NAD": {Name: "Namibian Dollar", Symbol: "NAD"},
	"NGN": {Name: "Nigerian Naira", Symbol: "NGN"},
	"NIO": {Name: "Nicaraguan Córdoba", Symbol: "NIO"},
	"NOK": {Name: "Norwegian Krone", Symbol: "kr"},
	"NPR": {Name: "Nepalese Rupee", Symbol: "NPR"},
	"NZD": {Name: "New Zealand Dollar", Symbol: "NZ$"},
	"OMR": {Name: "Omani Rial", Symbol: "OMR"},
	"PAB": {Name: "Panamanian Balboa", Symbol: "PAB"},
	"PEN": {Name: "Peruvian Nuevo Sol", Symbol: "PEN"},
	"PGK": {Name: "Papua New Guinean Kina", Symbol: "PGK"},
	"PHP": {Name: "Philippine Peso", Symbol: "₱"},
	"PKR": {Name: "Pakistani Rupee", Symbol: "PKR"},
	"PLN": {Name: "Polish Zloty", Symbol: "zł"},
	"PYG": {Name: "Paraguayan Guarani", Symbol: "PYG"},
	"QAR": {Name: "Qatari Rial", Symbol: "QAR"},
	"RON": {Name: "Romanian Leu", Symbol: "RON"},
	"RSD": {Name: "Serbian Dinar", Symbol: "RSD"},
	"RUB": {Name: "Russian Ruble", Symbol: "₽"},
	"RWF": {Name: "Rwandan Franc", Symbol: "RWF"},
	"SAR": {Name: "Saudi Riyal", Symbol: "﷼"},
	"SBD": {Name: "Solomon Islands Dollar", Symbol: "SBD"},
	"SCR": {Name: "Seychellois Rupee", Symbol: "SCR"},
	"SDG": {Name: "Sudanese Pound", Symbol: "SDG"},
	"SEK": {Name: "Swedish Krona", Symbol: "kr"},
	"SGD": {Name: "Singapore Dollar", Symbol: "S$"},
	"SHP": {Name: "Saint Helena Pound", Symbol: "SHP"},
	"SLE": {Name: "Sierra Leonean Leone", Symbol: "SLE"},
	"SOS": {Name: "Somali Shilling", Symbol: "SOS"},
	"SRD": {Name: "Surinamese Dollar", Symbol: "SRD"},
	"SSP": {Name: "South Sudanese Pound", Symbol: "SSP"},
	"STN": {Name: "São Tomé and Príncipe Dobra", Symbol: "STN"},
	"SVC": {Name: "Salvadoran Colón", Symbol: "SVC"},
	"SYP": {Name: "Syrian Pound", Symbol: "SYP"},
	"SZL": {Name: "Swazi Lilangeni", Symbol: "SZL"},
	"THB": {Name: "Thai Baht", Symbol: "฿"},
	"TJS": {Name: "Tajikistani Somoni", Symbol: "TJS"},
	"TMT": {Name: "Turkmenistani Manat", Symbol: "TMT"},
	"TND": {Name: "Tunisian Dinar", Symbol: "TND"},
	"TOP": {Name: "Tongan Paʻanga", Symbol: "TOP"},
	"TRY": {Name: "Turkish Lira", Symbol: "₺"},
	"TTD": {Name: "Trinidad and Tobago Dollar", Symbol: "TTD"},
	"TWD": {Name: "New Taiwan Dollar", Symbol: "TWD"},
	"TZS": {Name: "Tanzanian Shilling", Symbol: "TZS"},
	"UAH": {Name: "Ukrainian Hryvnia", Symbol: "UAH"},
	"UGX": {Name: "Ugandan Shilling", Symbol: "UGX"},
	"USD": {Name: "United States Dollar", Symbol: "$"},
	"USN": {Name: "US Dollar (Next day)", Symbol: "USN"},
	"UYI": {Name: "Uruguay Peso en Unidades Indexadas", Symbol: "UYI"},
	"UYU": {Name: "Uruguayan Peso", Symbol: "UYU"},
	"UYW": {Name: "Unidad Previsional", Symbol: "UYW"},
	"UZS": {Name: "Uzbekistan Som", Symbol: "UZS"},
	"VED": {Name: "Venezuelan Bolívar Digital", Symbol: "VED"},
	"VES": {Name: "Venezuelan Bolívar", Symbol: "VES"},
	"VND": {Name: "Vietnamese Dong", Symbol: "VND"},
	"VUV": {Name: "Vanuatu Vatu", Symbol: "VUV"},
	"WST": {Name: "Samoan Tala", Symbol: "WST"},
	"XAF": {Name: "CFA Franc BEAC", Symbol: "XAF"},
	"XAG": {Name: "Silver", Symbol: "XAG"},
	"XAU": {Name: "Gold", Symbol: "XAU"},
	"XBA": {Name: "European Composite Unit", Symbol: "XBA"},
	"XBB": {Name: "European Monetary Unit", Symbol: "XBB"},
	"XBC": {Name: "European Unit of Account 9", Symbol: "XBC"},
	"XBD": {Name: "European Unit of Account 17", Symbol: "XBD"},
	"XCD": {Name: "East Caribbean Dollar", Symbol: "XCD"},
	"XDR": {Name: "Special Drawing Rights", Symbol: "XDR"},
	"XOF": {Name: "CFA Franc BCEAO", Symbol: "XOF"},
	"XPD": {Name: "Palladium", Symbol: "XPD"},
	"XPF": {Name: "CFP Franc", Symbol: "XPF"},
	"XPT": {Name: "Platinum", Symbol: "XPT"},
	"XSU": {Name: "Sucre", Symbol: "XSU"},
	"XTS": {Name: "Testing Code", Symbol: "XTS"},
	"XUA": {Name: "ADB Unit of Account", Symbol: "XUA"},
	"XXX": {Name: "No Currency", Symbol: "XXX"},
	"YER": {Name: "Yemeni Rial", Symbol: "YER"},
	"ZAR": {Name: "South African Rand", Symbol: "R"},
	"ZMW": {Name: "Zambian Kwacha", Symbol: "ZMW"},
	"ZWG": {Name: "Zimbabwe Gold", Symbol: "ZWG"},
}
