package currency

// CurrencyWebsiteLanguages maps ISO 4217 currency codes to website locale tags.
var CurrencyWebsiteLanguages = map[string][]string{
	"AED": {"ar", "en"},
	"AFN": {"fa", "ps"},
	"ALL": {"sq"},
	"AMD": {"hy"},
	"AOA": {"pt"},
	"ARS": {"es"},
	"AUD": {"en"},
	"AWG": {"nl", "pap"},
	"AZN": {"az"},
	"BAM": {"bs", "hr", "sr"},
	"BBD": {"en"},
	"BDT": {"bn"},
	"BGN": {"bg"},
	"BHD": {"ar"},
	"BIF": {"fr", "rn"},
	"BMD": {"en"},
	"BND": {"ms", "en"},
	"BOB": {"es"},
	"BOV": {"es"},
	"BRL": {"pt"},
	"BSD": {"en"},
	"BTN": {"dz"},
	"BWP": {"en", "tn"},
	"BYN": {"be", "ru"},
	"BZD": {"en"},
	"CAD": {"en", "fr"},
	"CDF": {"fr"},
	"CHE": {"de", "fr", "it", "rm"},
	"CHF": {"de", "fr", "it", "rm"},
	"CHW": {"de", "fr"},
	"CLF": {"es"},
	"CLP": {"es"},
	"CNY": {"zh"},
	"COP": {"es"},
	"COU": {"es"},
	"CRC": {"es"},
	"CUC": {"es"},
	"CUP": {"es"},
	"CVE": {"pt"},
	"CZK": {"cs"},
	"DJF": {"fr", "ar"},
	"DKK": {"da"},
	"DOP": {"es"},
	"DZD": {"ar"},
	"EGP": {"ar"},
	"ERN": {"ti", "ar", "en"},
	"ETB": {"am", "om"},
	"EUR": {"bg", "cs", "da", "de", "el", "en", "es", "et", "fi", "fr", "ga", "hr", "hu", "it", "lt", "lv", "mt", "nl", "pl", "pt", "ro", "sk", "sl", "sv"},
	"FJD": {"en", "fj"},
	"FKP": {"en"},
	"GBP": {"en"},
	"GEL": {"ka"},
	"GHS": {"en"},
	"GIP": {"en"},
	"GMD": {"en"},
	"GNF": {"fr"},
	"GTQ": {"es"},
	"GYD": {"en"},
	"HKD": {"zh", "en"},
	"HNL": {"es"},
	"HTG": {"fr", "ht"},
	"HUF": {"hu"},
	"IDR": {"id"},
	"ILS": {"he", "ar"},
	"INR": {"hi", "en"},
	"IQD": {"ar"},
	"IRR": {"fa"},
	"ISK": {"is"},
	"JMD": {"en"},
	"JOD": {"ar"},
	"JPY": {"ja"},
	"KES": {"en", "sw"},
	"KGS": {"ky", "ru"},
	"KHR": {"km"},
	"KMF": {"ar", "fr"},
	"KPW": {"ko"},
	"KRW": {"ko"},
	"KWD": {"ar"},
	"KYD": {"en"},
	"KZT": {"kk", "ru"},
	"LAK": {"lo"},
	"LBP": {"ar"},
	"LKR": {"si", "ta"},
	"LRD": {"en"},
	"LSL": {"en", "st"},
	"LYD": {"ar"},
	"MAD": {"ar", "ber"},
	"MDL": {"ro"},
	"MGA": {"mg", "fr"},
	"MKD": {"mk"},
	"MMK": {"my"},
	"MNT": {"mn"},
	"MOP": {"zh", "pt"},
	"MRU": {"ar"},
	"MUR": {"en", "fr"},
	"MVR": {"dv"},
	"MWK": {"en", "ny"},
	"MXN": {"es"},
	"MXV": {"es"},
	"MYR": {"ms"},
	"MZN": {"pt"},
	"NAD": {"en", "af"},
	"NGN": {"en"},
	"NIO": {"es"},
	"NOK": {"no", "nb", "nn"},
	"NPR": {"ne"},
	"NZD": {"en", "mi"},
	"OMR": {"ar"},
	"PAB": {"es"},
	"PEN": {"es"},
	"PGK": {"en", "tpi", "ho"},
	"PHP": {"fil", "en"},
	"PKR": {"ur", "en"},
	"PLN": {"pl"},
	"PYG": {"es", "gn"},
	"QAR": {"ar"},
	"RON": {"ro"},
	"RSD": {"sr"},
	"RUB": {"ru"},
	"RWF": {"rw", "en", "fr"},
	"SAR": {"ar"},
	"SBD": {"en"},
	"SCR": {"en", "fr"},
	"SDG": {"ar", "en"},
	"SEK": {"sv"},
	"SGD": {"en", "ms", "zh", "ta"},
	"SHP": {"en"},
	"SLE": {"en"},
	"SOS": {"so", "ar"},
	"SRD": {"nl"},
	"SSP": {"en"},
	"STN": {"pt"},
	"SVC": {"es"},
	"SYP": {"ar"},
	"SZL": {"en", "ss"},
	"THB": {"th"},
	"TJS": {"tg"},
	"TMT": {"tk"},
	"TND": {"ar"},
	"TOP": {"to", "en"},
	"TRY": {"tr"},
	"TTD": {"en"},
	"TWD": {"zh"},
	"TZS": {"sw", "en"},
	"UAH": {"uk"},
	"UGX": {"en", "sw"},
	"USD": {"en", "es"},
	"USN": {"en"},
	"UYI": {"es"},
	"UYU": {"es"},
	"UYW": {"es"},
	"UZS": {"uz"},
	"VED": {"es"},
	"VES": {"es"},
	"VND": {"vi"},
	"VUV": {"bi", "en", "fr"},
	"WST": {"sm", "en"},
	"XAF": {"fr"},
	"XAG": {},
	"XAU": {},
	"XBA": {},
	"XBB": {},
	"XBC": {},
	"XBD": {},
	"XCD": {"en"},
	"XDR": {"en"},
	"XOF": {"fr"},
	"XPD": {},
	"XPF": {"fr"},
	"XPT": {},
	"XSU": {"es"},
	"XTS": {},
	"XUA": {"en"},
	"XXX": {},
	"YER": {"ar"},
	"ZAR": {"af", "en", "nr", "st", "tn", "ts", "ve", "xh", "zu"},
	"ZMW": {"en"},
	"ZWG": {"en", "sn", "nd"},
}

func WebsiteLanguagesForCurrency(code string) []string {
	languages, ok := CurrencyWebsiteLanguages[NormalizeCode(code)]
	if !ok {
		return nil
	}

	return append([]string(nil), languages...)
}
